### ISSUE TITLE
`boundedline(...)` does not plot using the current colororder 

### ISSUE THREAD

**Issue by sandshrew118** [kakearney/boundedline-pkg#12]
I have used the following simple example
```
figure
hold on
boundedline(linspace(0, 2*pi, 100), sin(linspace(0, 2*pi, 100)), sin(linspace(0, 2*pi, 100)) .* rand(1, 100), 'alpha')
boundedline(linspace(0, 2*pi, 100), cos(linspace(0, 2*pi, 100)), cos(linspace(0, 2*pi, 100)) .* rand(1, 100), 'alpha')
```

which outputs:
![image](https://user-images.githubusercontent.com/13067634/209985645-475fd8c5-3246-42df-9cf7-6a5cb639fd38.png)

However, I expected this to follow the default `colororder`, which is usually blue, then orange. Rather, it should follow the current `colororder`.

Details:
- your version of Matlab and all relevant toolboxes (type ver at the Matlab command line to get this info)
```plaintext
-----------------------------------------------------------------------------------------------------------------------
MATLAB Version: 9.12.0.2039608 (R2022a) Update 5
Operating System: Linux 6.0.12-76060006-generic #202212290932~1671652965~22.04~452ea9d SMP PREEMPT_DYNAMIC Wed D x86_64
Java Version: Java 1.8.0_202-b08 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
-----------------------------------------------------------------------------------------------------------------------
MATLAB                                                Version 9.12        (R2022a)
Parallel Computing Toolbox                            Version 7.6         (R2022a)
```

**Comment by sandshrew118** [comment]
I have found a solution involving setting the colours manually
```

colors = colororder( jet(8) );
figure
hold on
[l1, p1] = boundedline(linspace(0, 2*pi, 100), sin(linspace(0, 2*pi, 100)), sin(linspace(0, 2*pi, 100)) .* rand(1, 100), 'alpha')
[l2, p2] = boundedline(linspace(0, 2*pi, 100), cos(linspace(0, 2*pi, 100)), cos(linspace(0, 2*pi, 100)) .* rand(1, 100), 'alpha')

l1.Color = colors(1, :)
p1.FaceColor = colors(1, :)
outlinebounds(l1, p1)
l2.Color = colors(2, :)
p2.FaceColor = colors(2, :)
outlinebounds(l2, p2)
```

![image](https://user-images.githubusercontent.com/13067634/209989300-94902603-3bb9-466f-99e1-8b9787039214.png)

**Comment by kakearney** [comment]
The ‘cmap’ input parameter allows you to set the color order.  In your example, you could pass a single color for each call to bounded line. (If you plot multiple bounded lines in one call, it will fall back on the default color order, as you expected).

**Comment by sandshrew118** [comment]
Hi, yes thank you I have managed to reproduce the result as you suggested!
