### ISSUE TITLE
"hold 'off'" does not have an effect

### ISSUE THREAD

**Issue by MLackner** [kakearney/boundedline-pkg#5]
The hold command does not work with boundedline.

Sample code:

```matlab
% Make some data
x = linspace(0, 2*pi, 50);
y_raw = randn(20, 50, 2) + sin(x);
y_mean = squeeze(mean(y_raw, 1));
y_std = squeeze(std(y_raw, 1));

% Plot
fh = figure();
ah = axes(fh);
for i=1:2
    hold(ah, 'off')
    boundedline(x, y_mean(:,i)+2*i, y_std(:,i))
    pause(2)
end
```

This show a figure window plopping up, showing the first plot and then replace it with a second plot.
However, the first plot remains in the axes. Is this behaviour intended?

There is workaround with `cla(ah)`.

**Comment by kakearney** [comment]
This is the intended behavior of boundedline, which functions as a low-level plotting function (see [the Matlab docs](https://www.mathworks.com/help/matlab/creating_plots/role-of-graphics-objects.html#bucf5dn-3) for an explanation of high- vs. low-level plotting).

You'll notice the same behavior if you replace the call to boundedline with a low-level line plot:

```matlab
fh = figure();
ah = axes(fh);
for i=1:2
    hold(ah, 'off')
    line(x, y_mean(:,i)+2*i)
    pause(2)
end
```
